# Generated by the Kete Code release workflow (packages/kete-tools/src/distribute.ts in the
# Kete Code repository) for kete-v0.2.4. Don't edit: the next release replaces it.
class Kete < Formula
  desc "AI coding agent for the terminal"
  homepage "https://github.com/kete-org/kete-releases"
  version "0.2.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.4/kete-0.2.4-darwin-arm64.zip"
      sha256 "6148eef2b39d98e5e6845f97e0356f0b809bf4785a6ba877f776625d882fbb2d"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.4/kete-0.2.4-darwin-x64-baseline.zip"
      sha256 "4fa979fec8c28cb4f9f2ec7e1ada001d9abb84c40b8faebdfdcf8ffe3fb90aed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.4/kete-0.2.4-linux-arm64.tar.gz"
      sha256 "cfbb184a0482a4f07f8df9878b91673088a1edcfd1acbaace9e984d08d13c8e5"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.4/kete-0.2.4-linux-x64-baseline.tar.gz"
      sha256 "5c244bf60a1bca8af932d6afeecaffce98f7a466128ffc4536132ffb232f6abc"
    end
  end

  def install
    bin.install "kete"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kete --version")
  end
end
