# Generated by the Kete Code release workflow (packages/kete-tools/src/distribute.ts in the
# Kete Code repository) for kete-v0.2.0. Don't edit: the next release replaces it.
class Kete < Formula
  desc "AI coding agent for the terminal"
  homepage "https://github.com/kete-org/kete-releases"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.0/kete-0.2.0-darwin-arm64.zip"
      sha256 "0f431ec6de6106535fbd911414bb138343ec79926ca4c765e8f7c5507cf6565c"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.0/kete-0.2.0-darwin-x64-baseline.zip"
      sha256 "52612918751c5247ed49e927f3660ee6750eda5aca61120a753684cf69de0acc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.0/kete-0.2.0-linux-arm64.tar.gz"
      sha256 "8d64626b999442c8589ce0fd0cf98c3c24fda4011d15874c5dfcc70e6724f26e"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.0/kete-0.2.0-linux-x64-baseline.tar.gz"
      sha256 "600cfb4e6a6872b9739a093d3326c101ca86818d128cc4c43cb0cb7c579a74e3"
    end
  end

  def install
    bin.install "kete"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kete --version")
  end
end
