# Generated by the Kete Code release workflow (packages/kete-tools/src/distribute.ts in the
# Kete Code repository) for kete-v0.2.6. Don't edit: the next release replaces it.
class Kete < Formula
  desc "AI coding agent for the terminal"
  homepage "https://github.com/kete-org/kete-releases"
  version "0.2.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.6/kete-0.2.6-darwin-arm64.zip"
      sha256 "a830090ca3117c66f553d14b5b2119664696ec3d964b694be2d152e888bdcbdd"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.6/kete-0.2.6-darwin-x64-baseline.zip"
      sha256 "aa94f704c4351c53d5793029f87dc4305eeef5ac512ef73eeea19690771479a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.6/kete-0.2.6-linux-arm64.tar.gz"
      sha256 "fddc58dda6bb9b2db6d3c3514dfe454c0406d202891d2167c2e49b9ec2c8a6b6"
    end
    on_intel do
      url "https://github.com/kete-org/kete-releases/releases/download/kete-v0.2.6/kete-0.2.6-linux-x64-baseline.tar.gz"
      sha256 "cb295104419ddd3ed09e53d299a136ddd981beb4fb53d718fd5cd6659de6c4c9"
    end
  end

  def install
    bin.install "kete"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kete --version")
  end
end
